### Get all drivers
GET http://localhost:5000/api/drivers

### Get drivers by ID
GET http://localhost:5000/api/drivers/3

### Create new drivers
POST http://localhost:5000/api/drivers
Content-Type: application/json

{
    "carMake": "VW",
  "carModel": "ts",
  "carYear": 2020,
  "userId": 1,
  "online": false,
  "delivering": true
}

### Update existing drivers
PUT http://localhost:5000/api/drivers/7
Content-Type: application/json

{
    "carMake": "VW",
  "carModel": "TX",
  "carYear": 2024,
  "userId": 1,
  "online": false,
  "delivering": true
}

### Delete drivers
DELETE http://localhost:5000/api/drivers/3