### Get all addresses
GET http://localhost:5000/api/addresses

### Get address by ID
GET http://localhost:5000/api/addresses/3

### Create new address
POST http://localhost:5000/api/addresses
Content-Type: application/json

{
    "streetAddress1": "Main St",
  "streetAddress2": "Apt 675",
  "zipCode": "90201",
  "deliveryInstructions": "Leave at roof",
  "userId": 1,
  "cityId": 1
}

### Update existing address
PUT http://localhost:5000/api/addresses/5
Content-Type: application/json

{
    "cityId": 1,
    "zipCode": "12345",
    "streetAddress1": "123 Main St Updated",
    "streetAddress2": "Apt 101",
    "userId": 1,
    "deliveryInstructions": "Leave at front desk"
}

### Delete address
DELETE http://localhost:5000/api/addresses/5

